// Generated by `opennextjs-cloudflare build` before Wrangler bundles this
// entrypoint. It remains out of source control by design.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore generated deployment artifact
import openNextWorker from "../.open-next/worker.js";
import { refreshFirmsCache, type FirmsIngestEnv } from "./firms-ingest";

interface AppEnv extends FirmsIngestEnv {
  ASSETS: unknown;
  DATA_SOURCE: string;
}

interface WorkerExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
}

const appWorker = {
  fetch(request: Request, env: AppEnv, ctx: WorkerExecutionContext): Promise<Response> {
    return openNextWorker.fetch(request, env, ctx);
  },

  scheduled(_controller: unknown, env: AppEnv, ctx: WorkerExecutionContext): void {
    ctx.waitUntil(refreshFirmsCache(env).catch((error: unknown) => {
      console.error("FIRMS scheduled refresh failed; existing KV snapshot was preserved", error);
    }));
  },
};

export default appWorker;
