// Generated by `opennextjs-cloudflare build` before Wrangler bundles this
// entrypoint. It remains out of source control by design.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore generated deployment artifact
import openNextWorker from "../.open-next/worker.js";
import { runScheduled, type ScheduledEnv, type ScheduledSummary } from "./scheduled";
import { createAlertChannels, type AlertChannelEnv } from "../src/lib/monitoring/alert-channels";
import type { IngestHealthRecord } from "../src/lib/wildfire/ingest-health";

interface AppEnv extends ScheduledEnv, AlertChannelEnv {
  ASSETS: unknown;
}

interface WorkerExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
}

interface ScheduledController {
  cron: string;
}

/** Operational fields only; never upstream text, URLs or keys. */
function describe(health: IngestHealthRecord | undefined) {
  if (!health) return null;
  return {
    outcome: health.outcome,
    errorCode: health.errorCode ?? null,
    consecutiveFailures: health.consecutiveFailures,
    sourceRows: health.sourceRows ?? null,
    selectedPoints: health.selectedPoints ?? null,
  };
}

function logSummary(cron: string, summary: ScheduledSummary): void {
  const entry = {
    cron,
    firms: describe(summary.firms?.health),
    anepc: describe(summary.anepc?.health),
    alerts: [...(summary.firms?.alerts ?? []), ...(summary.anepc?.alerts ?? [])].map((alert) => `${alert.source}:${alert.event}`),
    digestSent: summary.digestSent,
  };
  const failed = summary.firms?.health.outcome === "failure" || summary.anepc?.health.outcome === "failure";
  if (failed) console.error("Scheduled refresh had a failure; the last known-good snapshots were kept", entry);
  else console.log("Scheduled refresh succeeded", entry);
}

const appWorker = {
  fetch(request: Request, env: AppEnv, ctx: WorkerExecutionContext): Promise<Response> {
    return openNextWorker.fetch(request, env, ctx);
  },

  scheduled(controller: ScheduledController, env: AppEnv, ctx: WorkerExecutionContext): void {
    ctx.waitUntil(
      runScheduled(controller.cron, env, { channels: createAlertChannels(env) })
        .then((summary) => logSummary(controller.cron, summary))
        .catch((error: unknown) => {
          // Only the error name: messages from fetch failures can include the FIRMS URL and key.
          console.error("Scheduled refresh crashed", error instanceof Error ? error.name : "unknown");
        }),
    );
  },
};

export default appWorker;
